### ISSUE TITLE
while converting number "default" to BN.js instance, error: invalid number value. Value must be an integer, hexstring, BN or BigNumber instance. Note, decimals are not supported. 

### ISSUE THREAD

**Issue by pragmaticadam** [loomnetwork/loom-truffle-provider#5]
When I've supplied int truffle config:

    extdev_plasma_us1: {
      provider: function() {
        const privateKey = fs.readFileSync(path.join(__dirname, 'extdev_private_key'), 'utf-8')
        console.log(privateKey);
        console.log(path.join(__dirname, 'extdev_private_key'));
        const chainId = 'default'
        const writeUrl = 'http://127.0.0.1:46658/rpc'
        const readUrl = 'http://127.0.0.1:46658/query'
        return new LoomTruffleProvider(chainId, writeUrl, readUrl, privateKey)
      },
      network_id: '*'
    },

I see following output:

JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
Error: Error: [number-to-bn] **while converting number "default" to BN.js instance, error: invalid number value. Value must be an integer, hexstring, BN or BigNumber instance. Note, decimals are not supported. Given value: "default"**
    at toBN (/home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/utils.js:64:1)
    at Method.hexToNumber [as outputFormatter] (/home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/utils.js:234:1)
    at Method.formatOutput (/home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-method/src/index.js:163:1)
    at sendTxCallback (/home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-method/src/index.js:473:1)
    at /home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:147:1
    at LoomProvider.<anonymous> (/home/adam/Desktop/Blockchain/code/loom-contracts/node_modules/loom-js/src/loom-provider.ts:345:7)
    at step (/home/adam/Desktop/Blockchain/code/loom-contracts/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/adam/Desktop/Blockchain/code/loom-contracts/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/adam/Desktop/Blockchain/code/loom-contracts/node_modules/tslib/tslib.js:104:62)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by lukezhangstudio** [comment]
which version of loom-js are you using? we have a known error with 1.39.0 so please downgrade to 1.38.0 until we fix it.

**Comment by pragmaticadam** [comment]
@lukezhangstudio 
I do not use loom-js directly,  only loom related package that i use is 

    "loom-truffle-provider": "^0.10.0",

which then is used by:

    "truffle-hdwallet-provider": "^1.0.2",

in loom-truffle-provider (in my node_modules) i see declaration
    "loom-js": "^1.37.1"
and that matches version of loom-js I see in my node_modules
"_from": "loom-js@^1.37.1",
  "_id": "loom-js@1.37.3",
  "_inBundle": false,
  "_integrity": "sha512-WTVbA8D85Z2QXdQgi8pKqIZbq0FXrS2H06vxFOZDfn0hgwHyKGA+twymw9ADkRsNWrLSFL7AtY1gmF809KOjYQ==",
  "_location": "/loom-js",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "loom-js@^1.37.1",
    "name": "loom-js",
    "escapedName": "loom-js",
    "rawSpec": "^1.37.1",
    "saveSpec": null,
    "fetchSpec": "^1.37.1"
  },
  "_requiredBy": [
    "/loom-truffle-provider"
  ],
In case it is anyhow useful to You I use:


Truffle v5.0.1 (core: 5.0.1)
Solidity - 0.4.24 (solc-js)
Node v11.6.0

**Comment by eduardonunesp** [comment]
Looks like the `loom-truffle-provider` latest version isn't published on `npm`

**Comment by pragmaticadam** [comment]
> Looks like the `loom-truffle-provider` latest version isn't published on `npm`

which version it should be? 
I see there is 0.11.0 on npm but it is marked as beta.

**Comment by eduardonunesp** [comment]
Yep, that beta version has `"loom-js": "1.38.0"`

**Comment by pragmaticadam** [comment]
Well,
with loom-truffle-provider in version 0.11.0 there is kind of a progress, but not to big.

 truffle migrate --network extdev_plasma_us1
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
⚠️  Important ⚠️
**If you're using an HDWalletProvider, it must be Web3 1.0 enabled or your migration will hang.**


Starting migrations...
======================
> Network name:    'extdev_plasma_us1'
> Network id:      6944156129341
> Block gas limit: 0


1_initial_migration.js
======================
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key
JY4gray4mqMNhP7NwCuXmZZIs+Z7D0tf9edBbCc7RtXEPQDzFsPskNVrZSGs83n8IdzJkygTSlfk2kDShsqWKw==
/home/adam/Desktop/Blockchain/code/loom-contracts/extdev_private_key

   Deploying 'Migrations'
   ----------------------
Error:  *** Deployment Failed ***

**"Migrations" -- JSON-RPC Error -32601 (Method not found): undefined.**

    at /home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at _tickCallback (internal/process/next_tick.js:43:7)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
Truffle v5.0.1 (core: 5.0.1)
Node v11.6.0

**LOOM node executable 1.0.0+b499**

**Comment by pragmaticadam** [comment]
Error above is an error when I have runned migration against my local loom node. 

In loom node I see periodically:

I[01-24|12:24:18.394] HTTPJSONRPC                                  module=query-server method=query args="[default:0xDB69EEC8F3d9E77fea02A1678700f612936eF6Cb 0xC5d1847a03dA59407F27f8FE7981D240bff2dfD3 <[]uint8 Value> <vm.VMType Value>]" returns="[<[]uint8 Value> <error Value>]"
I[01-24|12:24:18.394] Served RPC HTTP response                     module=query-server method=POST url=/query status=200 duration=0 remoteAddr=127.0.0.1:51990


unfortunatelly extdev do not work so I can not check against it.

**Comment by eduardonunesp** [comment]
Could you please try with the newest version of `loom`
